CREATE TABLE [dbo].[APODERADO]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [Nombre] NVARCHAR(50) NOT NULL, 
    [Teléfono] NVARCHAR(50) NOT NULL, 
    [id_Alumno] INT NOT NULL, 
    CONSTRAINT [FK_APODERADO_ALUMNO] FOREIGN KEY ([id_Alumno]) REFERENCES [ALUMNO]([Id]) 
)
