CREATE TABLE [dbo].[INSCRITO]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [id_Alumno] INT NOT NULL, 
    [Cod_Curso] INT NOT NULL, 
    CONSTRAINT [FK_INSCRITO_ALUMNO] FOREIGN KEY ([id_Alumno]) REFERENCES [ALUMNO]([Id]), 
    CONSTRAINT [FK_INSCRITO_CURSO] FOREIGN KEY ([Cod_Curso]) REFERENCES [CURSO]([Cod])
)
